### ISSUE TITLE
Gocrack for kali linux

### ISSUE THREAD

**Issue by jalall331** [fireeye/gocrack#10]
Hi. Who can help me to install and configure gocrack on kali linux or on ubuntu.  step by step.
I see examples on docs files, but how and where i must write this configs i dont know.

**Comment by easytraveller** [comment]
I wrote how I build gocrack on MacOS in my github pages(but sorry, it is in Chinese,but I think there has been enough codes) I hope it will help you. visit:http://easytraveller.top/2017/11/03/GoCrack-How-to-build-it/

**Comment by jalall331** [comment]
Thank you very much. i am going to try same this

**Comment by jalall331** [comment]
Some commands not working on kali. Maybe only ubuntu all this will working

**Comment by tankbusta** [comment]
Hi @jalall331 All the configuration settings along with a description can be found here https://github.com/fireeye/gocrack/blob/master/docs/administrator/config.md. There are also some example/placeholder configs in the root of the docs folder. Both binaries for the worker and server have a `-config` flag and by default will look for a config in the `./configs/(server|worker).yaml` folder (the configs folder being in the same path as the binary).
