### ISSUE TITLE
Default server config cors->allowed_origins parameter does not get parsed

### ISSUE THREAD

**Issue by recon-ng** [fireeye/gocrack#11]
Hi, I've successfully build gocrack, using go 1.9 on Ubuntu 16.04 and have created default configs for the server and worker in gocrack/build/linux/amd64/configs. However, when I run './gocrack_server' from amd64/ I get the following error:

{"time":"2017-11-03T17:34:13-04:00","level":"fatal","error":"web_server.cors.allowed_origins must contain one or more domains","message":"Failed to initialize server"}

I believe the issue is that the default config supplied in this repository defines 'api_server' instead of the expected 'web_server' listed in gocrack/server/config.go:18

**Comment by tankbusta** [comment]
Argh, yes you are correct. It should be `web_server` not `api_server` (https://github.com/fireeye/gocrack/blob/master/server/config.go#L18). This was a last minute change and slipped my mind. I'll get this fixed ASAP, thank you!
