### ISSUE TITLE
Bug in Card picker

### ISSUE THREAD

**Issue by rvn2p** [fireeye/gocrack#14]
Hi,
when i select a GPU from one worker and then try to add another, all other workers with the same id appear to be selected as well  (same GPU name, same ids just different machines).

![card_picker](https://user-images.githubusercontent.com/20243819/32607946-d87220e0-c55a-11e7-9749-eb388c51fe65.png)

The Bug has no functional implication as picking workers from different machines is not implemented yet.

**Comment by tankbusta** [comment]
@rvn2p Can you check the output of the API call to /api/v2/workers has the expected output and that it's just a UI issue? Chrome/FF/Safari dev tools can show you the request/response easily.

Thanks!

**Comment by tankbusta** [comment]
We have several boxes in our cluster and haven't been able to replicate this. This is most likely caused with 2 boxes with the same hostname or two workers running on the same host.
