### ISSUE TITLE
Improve ssl certificate error reporting

### ISSUE THREAD

**Issue by recon-ng** [fireeye/gocrack#16]
When gocrack_server parses the configs/server.yaml config, it throws the same error when encountering issues with the ca certificate, child certificate, and email server certificate. This makes it difficult to troubleshoot certificate issues.

**Comment by tankbusta** [comment]
Unfortunately I just return the error that Go returns unless the CA certificate is not valid, then I just throw a generic error. You can see the relevant code here: https://github.com/fireeye/gocrack/blob/master/shared/tls.go#L13

Can you get an example of the error you were getting from an invalid certificate?

**Comment by skywizards** [comment]
2017-11-28T10:50:11+08:00 |DEBU| Starting Notification Engine
2017-11-28T10:50:11+08:00 |FATA| Failed to start server error="failed to build cert pool with ca certificate"

**Comment by tankbusta** [comment]
I've improved the SSL errors by indicating what config directive has the invalid data
