### ISSUE TITLE
Problem about ssl certificate configuriation

### ISSUE THREAD

**Issue by Mxiaoyu** [fireeye/gocrack#20]
Hi, everyone, can someone solve the problem. When I use the command, there is

>  "{"time":"2017-11-15T00:47:12-08:00","level":"fatal","error":"failed to build cert pool with ca certificate","message":"Failed to start server"}"

**Comment by allwithfly** [comment]
证书有问题吧。

**Comment by tksjk20** [comment]
Have you solved this problem?I meet it ,too.

**Comment by Mxiaoyu** [comment]
@tksjk20 I have solved the problem. There are two configures of certificate, one is the server, another is the email, both of them must be configured. The generation of certificate can follow this page 

> https://networklessons.com/uncategorized/openssl-certification-authority-ca-ubuntu-server/

**Comment by tksjk20** [comment]
Thank u！It's so  important for me😁
