### ISSUE TITLE
Feature Request - add timer for tasks

### ISSUE THREAD

**Issue by croustibaie** [fireeye/gocrack#31]
Hi,

It would be pretty convenient if we could set on timer on the password cracking tasks. So that multiple users don't have to wait for the previous tasks to end (which could  be very long). 

I'd be ready to contribute to the development of this feature if needed, you can contact me @jaybeehare on Twitter.

**Comment by tankbusta** [comment]
I definitely think this would be a useful feature to have - to allow a user to create a job that has a max runtime of N hours before it checkpoints and stops.

I honestly probably wont get around to adding features until Q2 (March/April) so if you want to try and tackle this, go ahead! I can make myself available on IRC or elsewhere for questions. I would probably start by adding this to the [workmgr](https://github.com/fireeye/gocrack/blob/master/server/workmgr/workmgr.go) as that is responsible for receiving the messages from the workers and dispatching them within the server.

**Comment by croustibaie** [comment]
Ok, I should be able to do it before you then, I'll dig into it soon. I can be found on freenode #crousti.

**Comment by tankbusta** [comment]
I'm tankbusta on freenode

**Comment by tankbusta** [comment]
This was added in PR #32
