### ISSUE TITLE
Build fails with Go related errors

### ISSUE THREAD

**Issue by allabert** [fireeye/gocrack#39]
Hello,

When trying to build gocrack on Ubuntu 16.04.4 LTS with golang 1.6 installed i get following error:

user@ubuntu:~/Downloads/gocrack$ make build
mkdir -p builds/
go build -tags """" -o builds/linux/amd64/gocrack_worker  -ldflags \
        "-X github.com/fireeye/gocrack/worker.CompileRev=71bd3e4 \
         -X github.com/fireeye/gocrack/worker.CompileTime=1519829721 \
         -X github.com/fireeye/gocrack/worker/engines/hashcat.HashcatVersion=" \
        cmd/gocrack_worker/*.go
cmd/gocrack_worker/worker.go:14:2: cannot find package "github.com/fireeye/gocrack/shared" in any of:
        /usr/lib/go-1.6/src/github.com/fireeye/gocrack/shared (from $GOROOT)
        ($GOPATH not set)
cmd/gocrack_worker/worker.go:15:2: cannot find package "github.com/fireeye/gocrack/worker" in any of:
        /usr/lib/go-1.6/src/github.com/fireeye/gocrack/worker (from $GOROOT)
        ($GOPATH not set)
cmd/gocrack_worker/worker.go:16:2: cannot find package "github.com/fireeye/gocrack/worker/child" in any of:
        /usr/lib/go-1.6/src/github.com/fireeye/gocrack/worker/child (from $GOROOT)
        ($GOPATH not set)
cmd/gocrack_worker/worker.go:17:2: cannot find package "github.com/fireeye/gocrack/worker/parent" in any of:
        /usr/lib/go-1.6/src/github.com/fireeye/gocrack/worker/parent (from $GOROOT)
        ($GOPATH not set)
cmd/gocrack_worker/worker.go:19:2: cannot find package "github.com/rs/zerolog" in any of:
        /usr/lib/go-1.6/src/github.com/rs/zerolog (from $GOROOT)
        ($GOPATH not set)
cmd/gocrack_worker/worker.go:20:2: cannot find package "github.com/rs/zerolog/log" in any of:
        /usr/lib/go-1.6/src/github.com/rs/zerolog/log (from $GOROOT)
        ($GOPATH not set)
Makefile:14: recipe for target 'build' failed
make: *** [build] Error 1
---------------------------------------------------------------------------------------
I suspect it might be related to missing Go ENV variables but i cant figure out to what i would have to set them.

Regards,
allabert

**Comment by tankbusta** [comment]
This is because your GOPATH is not setup correctly and the code must live within your GOPATH. Please read https://github.com/golang/go/wiki/GOPATH for more information. 

Once your GOPATH is properly configured, the code must live within $GOPATH/src/github.com/fireeye/gocrack. 

You should also look at upgrading your Go version as 1.6 is very old now (1.10 is out)
