### ISSUE TITLE
docker make failed

### ISSUE THREAD

**Issue by rsj123** [fireeye/gocrack#43]
Step 25/25 : CMD make BINDIR=/out
 ---> Running in 2714364cd641
 ---> c456a6ca3807
Removing intermediate container 2714364cd641
Successfully built c456a6ca3807
docker run --rm --net=host -e USER_ID=0 \
                -v /root/gocrack-master/docker/dist/gocrack:/out \
                -v /src/github.com/fireeye/gocrack:/go/src/github.com/fireeye/gocrack \
                gocrack/build
make: *** No targets specified and no makefile found.  Stop.
make: *** [gocrack] Error 2

**Comment by mdouchement** [comment]
According to the Makefile in the folder `docker`, you must use the Golang folders pattern:

```sh
export $GOPATH=somewhere # if not already exported

mkdir -p $GOPATH/src/github.com/fireeye/
git clone https://github.com/fireeye/gocrack.git
cd gocrack/docker
make build
```

**Comment by HugoPouliquen** [comment]
Yeah thanks man!

**Comment by tankbusta** [comment]
Sorry for the docker problems... It's just me on this project within the Company and I've had other duties in between this release and now. Q3 (starting monday) I should have some time to fix a lot of these pains when dealing with docker so stay tuned. 

I'm going to go ahead and close this. If you have anymore issues please use #44
