### ISSUE TITLE
Proposal: Move gocat to its own repository

### ISSUE THREAD

**Issue by jmmcatee** [fireeye/gocrack#50]
I have been working on some changes to gocat to support v4 and now looking at v5 and I think it might be helpful to have a separate repository just for it. Any interest in pull it out similar to the UI repository?

**Comment by tankbusta** [comment]
I'd prefer to keep it in this repo if it works for you. If you're working on a fork, just make sure all the work is in a branch named `feat/update_hashcat_to_v5` and we can PR it in here when you're done. 

Is there major changes in v5 that really breaks things?

**Comment by jmmcatee** [comment]
Have not gotten too much into it yet so not sure. I have v4 working pretty well in my local tests and looking to use gocat to replace my current plugin for hashcat in github.com/jmmcatee/cracklord. Thanks for the consideration.

**Comment by tankbusta** [comment]
Let me think about it some more and see what it'd take. When this was an internal FireEye project, it was actually separate and would certainly make it easier to support other versions of Hashcat.

**Comment by jmmcatee** [comment]
Supporting multiple versions was definitely one of the reasons as I'm not sure it will be easy to have one version that supports multiple hashcat versions, but my familiarity with cgo is limited.

**Comment by tankbusta** [comment]
@jmmcatee We will be moving gocat into it's own repository that will make it easier for contributions and use in other open source software. 

It'll live in https://github.com/fireeye/gocat
