### ISSUE TITLE
double free or corruption

### ISSUE THREAD

**Issue by jmmcatee** [fireeye/gocrack#54]
I have gocat running with Hashcat 5.1 with a few tweaks other have done and everything run alright until any of the destroy functions are called. At this point I get either "double free or corruption" or a "free(): corrupted unsorted chunks:" error. Anyone seen this before or have any idea what this could be? Everything works, including password cracking up to this point.

**Comment by jmmcatee** [comment]
It appears this issue is resolved if you do not call the hashcat destroy functions within a defer. Not sure why that matters.

**Comment by Dreikana** [comment]
Hi, please could you expand on that? I am having the same problem in many PCs
