### ISSUE TITLE
bug/feat: support hashcat v4.0

### ISSUE THREAD

**Issue by evandrix** [fireeye/gocrack#6]
@/gocrack $ `make build`
```
mkdir -p builds/
go build -tags """" -o builds/linux/amd64/gocrack_worker  -ldflags \
	"-X github.com/fireeye/gocrack/worker.CompileRev=1618023 \
	 -X github.com/fireeye/gocrack/worker.CompileTime=1509387780" \
	cmd/gocrack_worker/*.go
# github.com/fireeye/gocrack/gocat
../../../go/src/github.com/fireeye/gocrack/gocat/gocat.go:287:7: could not determine kind of name for C.EVENT_WEAK_HASH_ALL_CRACKED
../../../go/src/github.com/fireeye/gocrack/gocat/gocat.go:231:7: could not determine kind of name for C.EVENT_WEAK_HASH_POST
../../../go/src/github.com/fireeye/gocrack/gocat/gocat.go:229:7: could not determine kind of name for C.EVENT_WEAK_HASH_PRE
Makefile:14: recipe for target 'build' failed
make: *** [build] Error 2
```

@/hashcat-v4.0.0 $ `hashcat64 --opencl-info`
```
hashcat (v4.0.0) starting...

OpenCL Info:

Platform ID #1
  Vendor  : NVIDIA Corporation
  Name    : NVIDIA CUDA
  Version : OpenCL 1.2 CUDA 8.0.0

  Device ID #1
    Type           : GPU
    Vendor ID      : 32
    Vendor         : NVIDIA Corporation
    Name           : GeForce GTX 1080
    Version        : OpenCL 1.2 CUDA
    Processor(s)   : 20
    Clock          : 1733
    Memory         : 2028/8112 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 375.82
```

**Comment by tankbusta** [comment]
@evandrix hashcat 4.0 is pretty new (3 days ago) and looks like they changed a few things. I'll try and update it to support v4. To get it to compile in the meantime, you'll need to use v3.6.0

**Comment by tankbusta** [comment]
I have a branch up (feat/hc_4_support) that removes the 3 `EVENT_WEAK_HASH*` events removed in v4. Some quick testing shows it works but I'll hold off on merging the branch in until I do some more work with handling different HC versions

**Comment by stratuscyber** [comment]
I'm having a similar issue but I have built hashcat 3.6.0:

make
mkdir -p builds/
go build -tags """" -o builds/linux/amd64/gocrack_worker  -ldflags \
        "-X github.com/fireeye/gocrack/worker.CompileRev=d816985 \
         -X github.com/fireeye/gocrack/worker.CompileTime=1530149677 \
         -X github.com/fireeye/gocrack/worker/engines/hashcat.HashcatVersion=" \
        cmd/gocrack_worker/*.go
# github.com/fireeye/gocrack/gocat
gocat/gocat.go:287:7: could not determine kind of name for C.EVENT_WEAK_HASH_ALL_CRACKED
gocat/gocat.go:231:7: could not determine kind of name for C.EVENT_WEAK_HASH_POST
gocat/gocat.go:229:7: could not determine kind of name for C.EVENT_WEAK_HASH_PRE
Makefile:14: recipe for target 'build' failed
make: *** [build] Error 2

root@Miner12:~/go/src/github.com/fireeye/gocrack# hashcat --version
v3.6.0+

**Comment by tankbusta** [comment]
Closing this... we are in the middle of upgrading to 5.X

See #55
