### ISSUE TITLE
ERROR When building in Centos 7

### ISSUE THREAD

**Issue by Mxiaoyu** [fireeye/gocrack#8]
cmd/gocrack_worker/worker.go:14:2: cannot find package "github.com/fireeye/gocrack/shared" in any of:
	/usr/lib/golang/src/github.com/fireeye/gocrack/shared (from $GOROOT)
	/home/mjw/go/src/github.com/fireeye/gocrack/shared (from $GOPATH)
cmd/gocrack_worker/worker.go:15:2: cannot find package "github.com/fireeye/gocrack/worker" in any of:
	/usr/lib/golang/src/github.com/fireeye/gocrack/worker (from $GOROOT)
	/home/mjw/go/src/github.com/fireeye/gocrack/worker (from $GOPATH)
cmd/gocrack_worker/worker.go:16:2: cannot find package "github.com/fireeye/gocrack/worker/child" in any of:
	/usr/lib/golang/src/github.com/fireeye/gocrack/worker/child (from $GOROOT)
	/home/mjw/go/src/github.com/fireeye/gocrack/worker/child (from $GOPATH)
cmd/gocrack_worker/worker.go:17:2: cannot find package "github.com/fireeye/gocrack/worker/parent" in any of:
	/usr/lib/golang/src/github.com/fireeye/gocrack/worker/parent (from $GOROOT)
	/home/mjw/go/src/github.com/fireeye/gocrack/worker/parent (from $GOPATH)
cmd/gocrack_worker/worker.go:19:2: cannot find package "github.com/rs/zerolog" in any of:
	/usr/lib/golang/src/github.com/rs/zerolog (from $GOROOT)
	/home/mjw/go/src/github.com/rs/zerolog (from $GOPATH)
cmd/gocrack_worker/worker.go:20:2: cannot find package "github.com/rs/zerolog/log" in any of:
	/usr/lib/golang/src/github.com/rs/zerolog/log (from $GOROOT)
	/home/mjw/go/src/github.com/rs/zerolog/log (from $GOPATH)

**Comment by tankbusta** [comment]
Hi @Mxiaoyu this is related to a misconfigured Go environment. The environment variable GOPATH should be set to something like `~/code/golang/` and this code should be in a path like `~/code/golang/src/github.com/fireeye/gocrack`.

Check out https://github.com/golang/go/wiki/Setting-GOPATH for more information

**Comment by Mxiaoyu** [comment]
@tankbusta Thanks very much! That's done.
