### ISSUE TITLE
error when building on macos

### ISSUE THREAD

**Issue by py4h0n** [fireeye/gocrack#9]
make build
mkdir -p builds/
go build -tags """" -o builds/darwin/amd64/gocrack_worker  -ldflags \
		"-X github.com/fireeye/gocrack/worker.CompileRev=1618023 \
		 -X github.com/fireeye/gocrack/worker.CompileTime=1509696556" \
		cmd/gocrack_worker/*.go
github.com/fireeye/gocrack/gocat
ld: library not found for -lhashcat
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build] Error 2

but hashcat building seems right..
➜  hashcat-3.6.0 ./hashcat --opencl-info
hashcat () starting...

OpenCL Info:

Platform ID #1
  Vendor  : Apple
  Name    : Apple
  Version : OpenCL 1.2 (Sep  6 2017 16:05:06)

  Device ID #1
    Type           : CPU
    Vendor ID      : 4
    Vendor         : Intel
    Name           : Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Version        : OpenCL 1.2
    Processor(s)   : 8
    Clock          : 2200
    Memory         : 4096/16384 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 1.1

  Device ID #2
    Type           : GPU
    Vendor ID      : 4
    Vendor         : Intel
    Name           : Iris Pro
    Version        : OpenCL 1.2
    Processor(s)   : 40
    Clock          : 1200
    Memory         : 384/1536 MB allocatable
    OpenCL Version : OpenCL C 1.2
    Driver Version : 1.2(Sep 29 2017 19:15:12)

**Comment by easytraveller** [comment]
I also met this problem before.
This works for me.
1.Uninstall your hashcat first(I have installed hashcat via homebrew) - brew uninstall hashcat
2.git clone hashcat & git submodule update
3.Set SHARED to 1 in src/Makefile
4.make & make install
5.cp -r include/ /usr/local/include/hashcat
After these I can `make build` in gocrack
Before you build you have to ensure there have "gocat"  and "zerolog" in your $GOPATH$

**Comment by tankbusta** [comment]
@easytraveller's instructions should fix it as it sounds like hashcat is not built as a shared library. (They're documented on this page https://github.com/fireeye/gocrack/blob/master/docs/building.md#step-1-building-hashcat).

You'll also want to make sure the code lives in a proper go workspace (as defined by the GOPATH environment variable). Mine is set to GOPATH="/Users/<username>/code/golang/" and the code should be in "/Users/<username>/code/golang/src/github.com/fireeye/gocrack". `go get -u github.com/fireeye/gocrack` should take care of downloading and setting up that folder hierarchy and will most likely complain about no buildable files but that can be ignored.
